### ISSUE TITLE
Probe method always returns false

### ISSUE THREAD

**Issue by exedor** [jdomnitz/net-mdns#37]
The Probe method is always returning false, even when there is a duplicate service on the network.

**Comment by jdomnitz** [comment]
Fixed and released as 0.33 on nuget

**Comment by exedor** [comment]
I'm not so sure this is fixed. I updated to the latest and tested again. It's still returning false. I'm testing by running 2 instances of a simple forms app with 1 button., which executes the code below after service discovery instance is created in the form constructor, like this:

`            _svcProfile = new("test1", "_testservice._tcp", 1234);
            _svcDiscovery = new();
`

. I start one in the debugger and one stand-alone so it's literally the identically same server. I press the Advertise button on the one running outside the debugger, then press the Advertise button on the one run by the debugger. I would expect the Probe call in the handler running in the debugger to return true, not false, indicating a duplicate was found. They are both using identical service profiles because they are literally the same application. Here's the code for the Advertise button handler where I have a breakpoint on the Debug.WriteLine call:

`            if (_svcDiscovery.Probe(_svcProfile))
                Debug.WriteLine("service conflict found!");
            else
                _svcDiscovery.Advertise(_svcProfile);
`
The breakpoint is never hit and the Debug output never happens.

**Comment by jdomnitz** [comment]
The unit tests are passing.  I think this may be a routing issue.

Can you try a quick test.  Reverse the order - Advertise in the first instance that you start (doesn't matter if it's debugger or standalone).  Then probe using the second instance started.  Does that work as expected?

**Comment by exedor** [comment]
I can, but ultimately, it shouldn't matter which button gets pressed in which instance first because whichever does the Probe first and gets false will Advertise (see button handler if/then statement), and the second in the other apps Probe *should* return true, but returns false again and only at that point are there 2 "advertisers." So what you asked is already how it is working, but sure I'll try it the other way around and then use a text box or something to indicate the Probe detected an existing conflict. Otherwise, I'll have no way of knowing.

**Comment by jdomnitz** [comment]
Sure!  I would be happy to take a look.

**Comment by exedor** [comment]
[DiscoveryServer-mDNS.zip](https://github.com/user-attachments/files/16128138/DiscoveryServer-mDNS.zip)

Many thanks!

**Comment by jdomnitz** [comment]
That confirms it is the port stealing issue.  I changed your debug line to a message box and ran 3 tests using the compiled EXEs:
Test 1) Open first instance, open second instance, advertise on second instance, then advertise on first instance. Successful probe error.
Test 2) Open first instance, open second instance, advertise on first instance, then advertise on second instance. Missing probe error.
Test 3) I re-tested on two separate machines and both orders worked correctly.

On windows, two sockets listening on the same port will share multicast traffic but steal unicast traffic. I confirmed that's what was happening using wireshark and the above tests. In a real environment these services would be on different interfaces or IP addresses so it's more of a debug annoyance. To make things easier I added a new option you can use when testing that disables unicast responses. It's technically not following the spec but it works fine in most cases.  New release is 0.34.

I updated your sample app to 0.34 and then added the following line to DiscoveryServer():
`MulticastService.EnableUnicastAnswers = false;`
That now works fine for advertising in either order on the same machine.

I am seeing an issue with Announcing that I am still working through.  That may be another bug fix (the joys of inheriting code).

**Comment by jdomnitz** [comment]
I'm sure plenty of others will run into the same issue so it's a useful feature to have.

> isn't it possible to restrict the server to specific interfaces

Yes if you create an instance of MulticastService you can include / exclude specific interfaces. The MulticastService instance then gets passed into the ServiceDiscovery constructor.

**I was able to track down the Announce bug (my fault).  0.35 should do what it is supposed to.  Let me know if you run into any other issues.**
